name: 'GADS Tests'
on: [ 'push', 'pull_request' ]

jobs:
  unit_tests:
    name: 'GADS Unit Tests'
    runs-on: 'ubuntu-20.04'
    timeout-minutes: 30

    steps:
      - name: 'Check out the GADS repository'
        uses: 'actions/checkout@v2'
      - name: 'Install Non-CPAN dependencies'
        run: |
          sudo apt-get install cpanminus liblua5.3-dev
          # Avoid "Install CPAN dependencies" needing to compile so much
          sudo apt-get install libdancer2-perl libdatetime-format-sqlite-perl libtest-most-perl libdatetime-set-perl libdbix-class-schema-loader-perl
      - name: 'Build cpanfile'
        run: |
          perl -wE 'our %prereq_pm; require "./Makefile.PL"; foreach my $k (sort keys %prereq_pm) { say qq(requires "$k";) }' > cpanfile
      - name: 'Install CPAN dependencies'
        uses: 'perl-actions/install-with-cpanm@v1'
        with:
          cpanfile: 'cpanfile'
      - name: 'Run the unit tests'
        run: |
          prove -lrs -j4 t

