name: 'GADS Tests'
on: [ 'push', 'pull_request' ]

jobs:
  webdriver_tests:
    name: 'Postgres Experiment'
    runs-on: 'ubuntu-20.04'
    timeout-minutes: 30

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespassword
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: 'Check out the GADS code'
        uses: 'actions/checkout@v2'
      - name: 'Install Non-CPAN dependencies'
        run: |
          sudo apt-get install libdbd-pg-perl
      - name: 'Set up credentials for psql'
        # See https://wiki.postgresql.org/wiki/Pgpass
        run: |
          echo '*:*:*:postgres:postgrespassword' > ~/.pgpass
          chmod 600 ~/.pgpass
      - name: 'Set up the application'
        env:
          PGDATABASE: 'postgres'
          PGHOST: 'localhost'
          PGUSER: 'postgres'
        run: ./bin/setup_for_webdriver
      - name: 'Connect to the database'
        env:
          PGHOST: 'localhost'
          PGUSER: 'linkspace'
          PGPASSWORD: 'linkspace'
        run: |
          perl -wE 'my $dbh = DBI->connect("dbi:Pg:database=linkspace"); $dbh->disconnect;'
