name: 'GADS Webdriver Tests'
on: [push]

jobs:
  webdriver:
    name: 'Webdriver Tests'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30

#    container:
#      # See https://github.com/Perl/docker-perl-tester
#      image: 'perldocker/perl-tester:5.32'

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      GADS_USERNAME: 'test@example.com'
      GADS_PASSWORD: 'xyz123'
      PGHOST: 'localhost'
      #PGPORT: ${{ job.services.postgres.ports[5432] }}

    steps:
      - name: 'Check out the GADS repository'
        uses: 'actions/checkout@v2'
      - name: 'Install Non-CPAN dependencies'
        run: |
          #cat /etc/apt/sources.list
          #cat /etc/apt/sources.list.d/*
          sudo apt-get install cpanminus liblua5.3-dev
          # sudo apt-get install firefox firefox-geckodriver liblua5.3-dev postgresql
      - name: 'Build cpanfile'
        run: |
          perl -wE 'our %prereq_pm; require "./Makefile.PL"; foreach my $k (sort keys %prereq_pm) { say qq(requires "$k";) }' > cpanfile
#      - name: 'Install CPAN dependencies'
#        uses: 'perl-actions/install-with-cpanm@v1'
#        with:
#          cpanfile: 'cpanfile'
      - name: 'Diagnostics'
        run: |
          netstat -4an
          echo 'select 1;' | psql
      - name: 'Start the application'
        run: ./bin/setup_for_webdriver
      - name: 'Run the Webdriver tests'
        run: prove -lmv webdriver/t/login.t
