on: [push]

jobs:
  webdriver:
    name: 'Webdriver Tests'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30

    container:
      # See https://github.com/Perl/docker-perl-tester
      image: 'perldocker/perl-tester:5.32'

    env:
      GADS_USERNAME: 'test@example.com'
      GADS_PASSWORD: 'xyz123'

    steps:
      - name: 'Check out the GADS repository'
        uses: 'actions/checkout@v2'
      - name: 'Build cpanfile'
        run: |
          perl -wE 'our %prereq_pm; require "./Makefile.PL"; foreach my $k (sort keys %prereq_pm) { say qq(requires "$k";) }' > cpanfile
      - name: 'Install Non-CPAN dependencies'
        run: |
          cat /etc/apt/sources
          cat /etc/apt/sources.list.d/*
          apt search gecko
          apt-get install firefox-esr firefox-geckodriver liblua5.3-dev postgresql
      - name: 'Install CPAN dependencies'
        uses: 'perl-actions/install-with-cpanm@v1'
        with:
          cpanfile: 'cpanfile'
          sudo: false
