name: 'Linkspace Tests'
on: 'push'

jobs:
#  unit:
#    name: 'Unit Tests'
#    runs-on: 'ubuntu-latest'
#    timeout-minutes: 15
#
#  steps:
#      - name: 'Check out the GADS repository'
#        uses: 'actions/checkout@v2'
#      - name: 'Install Non-CPAN dependencies'
#        run: sudo apt-get install cpanminus liblua5.3-dev
#      - name: 'Build cpanfile'
#        run: |
#          perl -wE 'our %prereq_pm; require "./Makefile.PL"; foreach my $k (sort keys %prereq_pm) { say qq(requires "$k";) }' > cpanfile
#      - name: 'Install CPAN dependencies'
#        uses: 'perl-actions/install-with-cpanm@v1'
#        with:
#          cpanfile: 'cpanfile'
#      - name: 'Run the unit tests'
#        run: prove -lrs -j4 t

  webdriver:
    name: 'Webdriver Tests'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30

    container:
      # See https://github.com/Perl/docker-perl-tester
      image: 'perldocker/perl-tester:5.32'

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespassword
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
# Skip health checks as subsequent build steps take a long time
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    env:
      GADS_USERNAME: 'test@example.com'
      GADS_PASSWORD: 'xyz123'
      PGDATABASE: 'postgres'
      PGUSER: 'postgres'

    steps:
      - name: 'Check out the Linkspace code'
        uses: 'actions/checkout@v2'
      - name: 'Install Non-CPAN dependencies'
        run: |
          apt-get -yq install liblua5.3-dev
      - name: 'Install CPAN dependencies'
        run: |
          cpanm --quiet --installdeps --notest .
          cd webdriver
          cpanm --quiet --installdeps --notest .
      - name: 'Set up credentials for psql'
        # See https://wiki.postgresql.org/wiki/Pgpass
        run: |
          echo '*:*:*:postgres:postgrespassword' > ~/.pgpass
          chmod 600 ~/.pgpass
      - name: 'Start the application'
        env:
          PGDATABASE: postgres
          PGHOST: localhost
          PGUSER: postgres
        run: ./bin/setup_for_webdriver
      - name: 'Run the Webdriver tests'
        #run: prove -lmrsv webdriver/t
        run: prove -lmv webdriver/t/login.t
