name: 'Linkspace Tests'
on: 'push'

jobs:
#  unit:
#    name: 'Unit Tests'
#    runs-on: 'ubuntu-latest'
#    timeout-minutes: 15
#
#  steps:
#      - name: 'Check out the GADS repository'
#        uses: 'actions/checkout@v2'
#      - name: 'Install Non-CPAN dependencies'
#        run: sudo apt-get install cpanminus liblua5.3-dev
#      - name: 'Build cpanfile'
#        run: |
#          perl -wE 'our %prereq_pm; require "./Makefile.PL"; foreach my $k (sort keys %prereq_pm) { say qq(requires "$k";) }' > cpanfile
#      - name: 'Install CPAN dependencies'
#        uses: 'perl-actions/install-with-cpanm@v1'
#        with:
#          cpanfile: 'cpanfile'
#      - name: 'Run the unit tests'
#        run: prove -lrs -j4 t

  webdriver:
    name: 'Webdriver Tests'
    #runs-on: 'ubuntu-latest'
    runs-on: 'ubuntu-20.04'
    timeout-minutes: 30

    container:
      # See https://github.com/Perl/docker-perl-tester
      image: 'perldocker/perl-tester:5.32'

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespassword
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    env:
      GADS_USERNAME: 'test@example.com'
      GADS_PASSWORD: 'xyz123'
      PGDATABASE: 'postgres'
      PGHOST: 'postgres'
      PGUSER: 'postgres'
      PGPASSWORD: 'postgrespassword'

    steps:
      - name: 'Check out the Linkspace code'
        uses: 'actions/checkout@v2'
      - name: 'Install Non-CPAN dependencies'
        run: |
          apt-get -yq install liblua5.3-dev postgresql-client
#      - name: 'Install CPAN dependencies'
#        run: |
#          cpanm --quiet --installdeps --notest .
#          cd webdriver
#          cpanm --quiet --installdeps --notest .
      - name: 'Start the application'
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
          tar -xf geckodriver-v0.28.0-linux64.tar.gz
          cp -rp geckodriver /usr/bin
          env
          which geckodriver
          MOZ_HEADLESS=1 geckodriver -p 9998 --log warn &
          ./bin/setup_for_webdriver
      - name: 'Run the Webdriver tests'
        # TODO: when webdriver/t/create_view.t passes - prove -lmrsv webdriver/t
        run: prove -lmv webdriver/t/login.t
